"""add filel: is_dead to table: death_sensor

Revision ID: 66596ffd82ac
Revises: d74b1af130e2
Create Date: 2023-10-08 13:29:06.949933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66596ffd82ac'
down_revision: Union[str, None] = 'd74b1af130e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_sensors', sa.Column('is_dead', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('death_sensors', 'is_dead')
    # ### end Alembic commands ###
