"""add model: DeathSensors

Revision ID: 9b9f0b79248c
Revises: 8df5466733ff
Create Date: 2023-10-07 16:53:05.258104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9f0b79248c'
down_revision: Union[str, None] = '8df5466733ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('death_sensors',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('datetime_event', sa.DateTime(), nullable=False),
    sa.Column('temperatures', sa.Float(), nullable=False),
    sa.Column('battery_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('death_sensors')
    # ### end Alembic commands ###
