"""add model: change field temperatures for temperatures on table death_sensors

Revision ID: d74b1af130e2
Revises: 9b9f0b79248c
Create Date: 2023-10-07 17:02:25.633999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74b1af130e2'
down_revision: Union[str, None] = '9b9f0b79248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_sensors', sa.Column('temperature', sa.Float(), nullable=False))
    op.drop_column('death_sensors', 'temperatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_sensors', sa.Column('temperatures', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('death_sensors', 'temperature')
    # ### end Alembic commands ###
