# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'communityaerial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for communityaerial
# CocoaPods
pod "Player", "~> 0.13.2"
pod ‘youtube-ios-player-helper’, ‘~> 0.1’


  target 'communityaerialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'communityaerialUITests' do
    # Pods for testing
  end

end
